### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/Bridge#3]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by ezequielpereira** [comment]
Eh... I'm not being able to do so:
"Users must have admin or owner rights within the receiving organization before they can transfer a repository that they individually own".

**Comment by davelab6** [comment]
You are in the https://github.com/orgs/sugarlabs/teams/temp-transfer-owners team so it should work. Did you accept the invitation at https://github.com/sugarlabs/ ?

**Comment by ezequielpereira** [comment]
I did, but it says "You don’t have admin rights to sugarlabs".

**Comment by davelab6** [comment]
Sorry! Try now :)

**Comment by ezequielpereira** [comment]
It allows me now.
I'm not sure which sugarlabs' teams should have access, so I'll let all of them have access the activity, then you fix it if it is wrong.

**Comment by davelab6** [comment]
Thanks! Do you have any other Sugar repos to transfer? :)

**Comment by ezequielpereira** [comment]
Yes, I do, I'll begin transferring them now. :)

**Comment by davelab6** [comment]
Okay great, please ping me here when done :) No rush

**Comment by ezequielpereira** [comment]
I finished transferring the ones indicated on https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub
There are a few more activities repos in my account, I am not sure if SugarLabs just missed them or discarded them because of something.

**Comment by davelab6** [comment]
I missed them :) If you would like the sugar community to discover and help develop them, please transfer :)

**Comment by ezequielpereira** [comment]
Done :).

**Comment by davelab6** [comment]
AWESOME! Thanks so much! I reset your status from owner to member, I hope that's ok :)

**Comment by davelab6** [comment]
BTW you might like to set your sugarlabs membership public 💃
